# Generated by Django 6.0.1 on 2026-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
